sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-dj20-postgres

    - stage: PyPI Release
      if: tag IS NOT present
      script: skip
      install: skip
      after_success: skip
      deploy: &pypi
        provider: pypi
        user: blueyed
        password:
          secure: "invalid"
        on:
          tags: false
        distributions: "sdist bdist_wheel"

  allow_failures:
    - env: TOXENV=py36-djmaster-postgres

install:
  # Create pip wrapper script, using travis_retry (a function) and
  # inject it into tox.ini.
  - mkdir -p bin
  - PATH=$PWD/bin:$PATH
  - printf '#!/bin/sh\n' > bin/travis_retry_pip
  - declare -f travis_retry >> bin/travis_retry_pip
  - printf '\necho "Using pip-wrapper.." >&2\ntravis_retry pip "$@"' >> bin/travis_retry_pip
  - chmod +x bin/travis_retry_pip
  - sed -i.bak 's/^\[testenv\]/\0\nwhitelist_externals = travis_retry_pip\ninstall_command = travis_retry_pip install {opts} {packages}/' tox.ini
  - if diff tox.ini tox.ini.bak; then exit 1; fi

  - pip install tox==2.9.1
  - |
    # Setup coverage tracking, but not with "checkqa" nor "pypy*".
    if [[ "$TOXENV" != "checkqa" ]] && [[ "${TOXENV#pypy}" == "$TOXENV" ]]; then
      PYTEST_DJANGO_COVERAGE=1
      export PYTEST_ADDOPTS='--cov=pytest_django --cov=tests --cov=pytest_django_test --cov-report=term-missing:skip-covered'
      export _PYTESTDJANGO_TOX_EXTRA_DEPS=pytest-cov
    else
      PYTEST_DJANGO_COVERAGE=0
    fi

script:
  - tox

after_success:
  - |
    set -ex
    if [[ "$PYTEST_DJANGO_COVERAGE" = 1 ]]; then
      pip install codecov

      coverage --version
      coverage combine
      coverage xml

      codecov_flags=${TOXENV//./}
      codecov_flags=${codecov_flags//-/ }
      codecov --required -X search gcov pycov -f coverage.xml --flags $codecov_flags
    fi
    set +x
