sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:
    # py37 is not available in trusty dist, and requires sudo=true with xenial.
    - stage: test
      python: 3.6
      env: TOXENV=py36-dj21-sqlite

stages:
  - name: test
    if: tag IS NOT present
  - name: test_release
    if: tag IS present
  - name: release
    if: tag IS present

install:
  - pip install tox==3.3.0
  - |
    # Setup coverage tracking.
    if [[ "$SKIP_COVERAGE" != "1" ]]; then
      PYTEST_DJANGO_COVERAGE=1
      export PYTEST_ADDOPTS='--cov=pytest_django --cov=tests --cov=pytest_django_test --cov-report=term-missing:skip-covered'
      export _PYTESTDJANGO_TOX_EXTRA_DEPS='https://github.com/pytest-dev/pytest-cov/archive/8eae2242df3ea8471187587e81ee97de3f65b7b0.tar.gz'
    else
      PYTEST_DJANGO_COVERAGE=0
    fi

script:
  - tox

after_success:
  - |
    set -ex
    if [[ "$PYTEST_DJANGO_COVERAGE" = 1 ]]; then
      pip install codecov

      coverage --version
      coverage combine
      coverage xml

      codecov_flags=${TOXENV//./}
      codecov_flags=${codecov_flags//-/ }
      codecov --required -X search gcov pycov -f coverage.xml --flags $codecov_flags
    fi
    set +x
